const ERROR_CODES = {
    SUCCESS: 'SUCCESS',
    FAILED: 'FAILED',
    AUTH_FAILED: 'AUTH_FAILED',
    NOT_FOUND: 'NOT_FOUND',
    NOT_ALLOWED: 'NOT_ALLOWED',
    ALREADY_PRESENT: 'ALREADY_PRESENT',
    INVALID_PARAMS: 'INVALID_PARAMS',
    INVALID_CREDENTIAL: 'INVALID_CREDENTIAL',
    PERMISSION_DENIED: 'PERMISSION_DENIED',
    RESET_PASSWORD: 'RESET_PASSWORD',
};

const USER_DEFAULT_ATTRIBUTE = ['userId', 'firstName', 'lastName', 'userEmail', 'phoneNumber', "address", "userRole"]

module.exports = {
    ERROR_CODES,
    USER_DEFAULT_ATTRIBUTE
}